### ISSUE TITLE
Enhanced descritpions/explanations of modules

### ISSUE THREAD

**Issue by gregors21** [rubrikinc/terraform-provider-polaris#145]
Customer is trying to automate deployments of Azure and AWS protection and there are components referenced with no description of what they are.

Customer is unable to fully automate deployment and create functional terraform code.

Is it possible to update the modules with a more detailed outline of the modules and components used?

Thanks

**Comment by johan3141592** [comment]
Documentation for AWS has been updated in `v0.9.0-beta.8`.
