### ISSUE TITLE
Azure Exocompute resource needs to support the new CNI overlay network configurations

### ISSUE THREAD

**Issue by DamaniN** [rubrikinc/terraform-provider-polaris#159]
**Is your feature request related to a problem? Please describe.**

Yes, there is no way to configure the CNI Overlay CIDR when adding Exocompute Host. 

**Describe the solution you'd like**

Support setting the CNI Overlay CIDRs when adding an Exocompute Host. 

**Describe alternatives you've considered**

Useing the GraphQL API to set this.

**Additional context**

See step 10 [here](https://docs.rubrik.com/en-us/saas/saas/adding_regions_azr_exocompute.html?hl=cidr).

**Comment by johan3141592** [comment]
The latest beta release (`v0.9.0-beta.2`) adds support for providing an overlay network CIDR address (`pod_overlay_network_cidr`) to the `polaris_azure_exocompute` resource. See the resource [documentation](https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/resources/azure_exocompute) for additional information.
