### ISSUE TITLE
Provide a Data Source for referencing a pre-existing Azure Subscription Resource

### ISSUE THREAD

**Issue by joeharlan** [rubrikinc/terraform-provider-polaris#183]
**Is your feature request related to a problem? Please describe.**

To create an Azure Archive Location resource it is requiring the use of the Rubrik-internal `cloud_account_id` string.  This is something used on the back-end of Rubrik to uniquely track the Subscription that has been onboarded, but is not referenceable in a TF plan unless the archive location and subscription onboarding modules are executed in the same plan.  Customers looking to factor their deployments with these two plans operating separately are unable to do so easily without first looking up the ID in another way.

**Describe the solution you'd like**

Provide a data source for the Azure Subscription that would allow the TF plan to reference details about the Rubrik Cloud Account representation of the Subscription.  This would enable the archive location code to easily reference the `cloud_account_id` value and solve the problem described above.

**Describe alternatives you've considered**

The only workaround is to locate the ID another way and provide it statically in the TF plan used to create the archive locations.

**Additional context**

.

**Comment by johan3141592** [comment]
In the `0.9.0-beta.10` release, there are two new data sources available:
 * https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/data-sources/aws_account 
 * https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/data-sources/azure_subscription

The data sources can be used to look up the cloud account ID for an AWS account or Azure subscription added to RSC.
