### ISSUE TITLE
Missing a list of feature keywords for Azure permissions

### ISSUE THREAD

**Issue by DamaniN** [rubrikinc/terraform-provider-polaris#83]
**Expected Behavior**

I expect to be able to configure permissions for Azure SQL, Azure MI, Azure Cloud Native Archival and Azure Cloud Native Archival with Encryption.

**Current Behavior**

Currently, under [docs/data-sources/azure_permissions.md ](https://github.com/rubrikinc/terraform-provider-polaris/blob/main/docs/data-sources/azure_permissions.md) the specific feature keywords that are supported are not listed.  By looking at the examples, I've seen that the keywords `cloud-native-protection` and `exocompute` are supported. The full list of supported keywords needs to be listed. The features that are missing are:

* Azure SQL
* Azure MI
* Cloud Native Archival 
* Cloud Native Archival Encryption

**Failure Information (for bugs)**

N/A

**Steps to Reproduce**

Read the documentation.

**Context**

Version [v0.8.0-beta.3](https://github.com/rubrikinc/terraform-provider-polaris/releases/tag/v0.8.0-beta.3) of the provider.

**Failure Logs**

N/A

**Comment by johan3141592** [comment]
@DamaniN the documentation for Azure has been improved. Please have a look at the docs for the latest beta release (`v0.10.0-beta.1`):
  * https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/data-sources/azure_permissions
  * https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/resources/azure_exocompute
  * https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/resources/azure_service_principal
  * https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/resources/azure_subscription

There is also a guide for how to upgrade to the latest beta from `v0.7.7`:
  * https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/guides/upgrade_guide_beta

Let me know what you think.
