### ISSUE TITLE
Support shared Exocompute on Azure

### ISSUE THREAD

**Issue by DamaniN** [rubrikinc/terraform-provider-polaris#84]
**Is your feature request related to a problem? Please describe.**

There's no way to configure shared Exocompute for Azure via the provider. 

**Describe the solution you'd like**

Provide a way to configure shared Exocompute for Azure in the provider. 

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by johan3141592** [comment]
Support for Azure shared Exocompute has been added to the latest beta release (`v0.9.0-beta.2`). The [documentation](https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/resources/azure_exocompute) for `polaris_azure_exocompute` has also been updated accordingly.
