### ISSUE TITLE
Support shared Exocompute on AWS

### ISSUE THREAD

**Issue by DamaniN** [rubrikinc/terraform-provider-polaris#93]
**Is your feature request related to a problem? Please describe.**

There's no way to configure shared Exocompute for AWS via the provider. 

**Describe the solution you'd like**

Provide a way to configure shared Exocompute for AWS in the provider. 

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by johan3141592** [comment]
This should be supported on the beta branch. Can we close this issue @DamaniN?

**Comment by DamaniN** [comment]
Yes this can be closed.
